apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cost-management-operator

resources:
  - namespace.yaml
  - subscription.yaml
  - costmanagementmetricsconfig.yaml

commonLabels:
  app.kubernetes.io/name: cost-management-operator
  app.kubernetes.io/component: cost-management
  app.kubernetes.io/part-of: healthcare-ml-demo
