apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: frontend-8bit-game
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  # Will contain:
  # - deployment.yaml
  # - service.yaml
  # - route.yaml

configMapGenerator:
  # Will contain:
  # - Frontend assets (index.html, app.js, style.css)

# Placeholder - resources will be added in Task 5
