apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vep-service-scaler
  namespace: healthcare-ml-demo
  labels:
    app.kubernetes.io/component: vep-service
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: vep-annotation-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vep-service
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    # Primary trigger: Kafka topic lag for genetic-data-raw
    - type: kafka
      metadata:
        bootstrapServers: genetic-data-cluster-kafka-bootstrap.healthcare-ml-demo.svc.cluster.local:9092
        consumerGroup: vep-service-group
        topic: genetic-data-raw
        lagThreshold: '5'
