module.exports = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'getting-started',
        'local-development',
        'first-genetic-analysis',
        'scaling-demo',
        'kafka-lag-scaling',
        'configure-keda',
        'debug-kafka',
        'troubleshoot-websocket',
        'node-scaling-cost-optimization',
        'red-hat-autoscaling-coordination-projects',
        'ADR-005-keda-troubleshooting-configuration',
        'ADR-006-vep-service-architecture-decision',
        'ADR-008-multi-dimensional-pod-autoscaler-development-phase',
      ],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      items: [
        'CURRENT_KEDA_STATUS',
        'KEDA_SEPARATION_OF_CONCERNS',
        'SEPARATION_VALIDATION_GUIDE',
        'ADR-001-correct-deployment-strategy-websocket-vep-services',
        'ADR-002-openshift-ai-integration-strategy',
        'ADR-003-healthcare-ml-ecosystem-architecture',
        'ADR-007-websocket-single-instance-requirement',
        'advanced-troubleshooting-augment',
        'monitor-costs',
        'deployment-script-integration',
        'deploy-openshift',
        'event-driven-design',
        'configuration',
        'keda-scaling',
        'github-project-management',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'quality-assurance-framework-augment',
        'quality-assurance-validation',
        'code-cleanup-analysis',
        'github-project-management-enhanced',
        'ADR-007-multi-topic-keda-node-scaling-architecture',
        'ADR-004-api-testing-validation-openshift',
        'validate-separation-of-concerns',
        'api-reference',
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      items: [
        'RQ2.7-Performance-Benchmarking-Framework',
        'keda-kafka-lag-scaling-vs-node-autoscaling',
        'RQ1.1-Threading-Patterns-Documentation',
        'RQ1.6-CloudEvent-Processing-Patterns',
      ],
    },
  ],
};