apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/part-of: healthcare-ml-demo
    app.kubernetes.io/managed-by: kustomize
  annotations:
    cost-center: "genomics-research"
    project: "risk-predictor-v1"
