apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: serverless-operator
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - subscription.yaml
  - knative-serving-namespace.yaml
  - knative-eventing-namespace.yaml
  - knative-serving.yaml
  - knative-eventing.yaml
