apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vep-service
  labels:
    app.kubernetes.io/component: vep-service
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: vep-annotation-v1
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: "3.8"
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/tosin2013/healthcare-ml-genetic-predictor.git"
      ref: "main"
    contextDir: "vep-service"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "java:openjdk-17-ubi8"
      env:
        - name: MAVEN_ARGS
          value: "clean package -DskipTests"
        - name: MAVEN_OPTS
          value: "-Xmx1024m"
        - name: ARTIFACT_COPY_ARGS
          value: "-p -r lib/ quarkus-app/"
  output:
    to:
      kind: ImageStreamTag
      name: "vep-service:latest"
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "vep-service-github-webhook"
    - type: Generic
      generic:
        secret: "vep-service-generic-webhook"
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: "java:openjdk-17-ubi8"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  postCommit: {}
  nodeSelector: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
