apiVersion: apps/v1
kind: Deployment
metadata:
  name: vep-service
  labels:
    app: vep-service  # For KEDA scaling selector
    app.kubernetes.io/component: vep-service
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: vep-annotation-v1
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: "3.8"
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"genetic-data-cluster-kafka"}]'
spec:
  replicas: 0  # KEDA will manage scaling based on Kafka lag
  selector:
    matchLabels:
      app.kubernetes.io/component: vep-service
      app.kubernetes.io/name: vep-annotation-service
  template:
    metadata:
      labels:
        app: vep-service  # For KEDA scaling selector
        app.kubernetes.io/component: vep-service
        app.kubernetes.io/name: vep-annotation-service
        app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
        app.kubernetes.io/version: "1.0.0"
      annotations:
        insights.openshift.io/billing-model: chargeback
        insights.openshift.io/cost-center: genomics-research
        insights.openshift.io/project: vep-annotation-v1
    spec:
      serviceAccountName: vep-service
      enableServiceLinks: false
      containers:
        - name: vep-service
          image: vep-service:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: vep-service-config
                  key: kafka.bootstrap.servers
            - name: VEP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: vep-service-config
                  key: vep.api.url
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: vep-service-config
                  key: quarkus.log.level
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: QUARKUS_HTTP_HOST
              value: "0.0.0.0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config-volume
              mountPath: /deployments/config
              readOnly: true

      # Node affinity for standard workload pool
      affinity:
        nodeAffinity:
          # Require standard workload nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload-type
                operator: In
                values: ["standard"]
          # Prefer balanced resource profile
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: resource-profile
                operator: In
                values: ["balanced"]
          - weight: 80
            preference:
              matchExpressions:
              - key: workload.healthcare-ml/mode
                operator: In
                values: ["normal-bigdata"]

        # Pod anti-affinity for better distribution
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - vep-service
              topologyKey: kubernetes.io/hostname

      volumes:
        - name: config-volume
          configMap:
            name: vep-service-config
