apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vep-service
  labels:
    app.kubernetes.io/component: vep-service
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: vep-annotation-v1
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: "3.8"
    openshift.io/display-name: "VEP Annotation Service"
    openshift.io/provider-display-name: "Healthcare ML Team"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations:
        openshift.io/display-name: "VEP Service (Latest)"
        description: "Latest build of the VEP annotation service"
        iconClass: "icon-quarkus"
        tags: "quarkus,java,vep,genetics,annotation"
        supports: "quarkus:3.8,java:17"
        version: "1.0.0"
      from:
        kind: DockerImage
        name: "image-registry.openshift-image-registry.svc:5000/healthcare-ml-demo/vep-service:latest"
      importPolicy:
        scheduled: false
      referencePolicy:
        type: Local
