apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vep-service
  annotations:
    config.kubernetes.io/local-config: "true"

# VEP Service Resources - ADR-001: Event-driven Knative service for auto-scaling
resources:
  # - deployment.yaml        # Removed per ADR-001: VEP uses Knative for event-driven scaling
  # - service.yaml          # Not needed: Knative service includes built-in service
  - knative-service.yaml    # ADR-001: VEP service uses Knative for cost-efficient scaling
  - configmap.yaml
  - buildconfig.yaml
  - imagestream.yaml

# VEP-specific labels
commonLabels:
  app.kubernetes.io/component: vep-service
  app.kubernetes.io/name: vep-annotation-service
  app.kubernetes.io/version: "1.0.0"

# VEP-specific annotations
commonAnnotations:
  app.openshift.io/runtime: quarkus
  app.openshift.io/runtime-version: "3.8"
  insights.openshift.io/billing-model: chargeback
  insights.openshift.io/cost-center: genomics-research
  insights.openshift.io/project: vep-annotation-v1
  deployment-method: "knative"     # ADR-001: Changed from deployment to knative
  adr-decision: "ADR-001"          # Track architectural decision

# VEP service image configuration
images:
  - name: vep-service
    newName: image-registry.openshift-image-registry.svc:5000/healthcare-ml-demo/vep-service
    newTag: latest

# ADR-001: Resource configuration moved to Knative service spec
# No patches needed - resources configured directly in knative-service.yaml
