apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vep-service
  annotations:
    config.kubernetes.io/local-config: "true"

# VEP Service Resources - Updated: Regular Deployment + KEDA for Kafka-based scaling
resources:
  - deployment.yaml         # Regular deployment for KEDA scaling
  - service.yaml            # Service for deployment
  - serviceaccount.yaml     # Service account for image pull permissions
  - configmap.yaml
  - buildconfig.yaml
  - imagestream.yaml

# VEP-specific labels
commonLabels:
  app.kubernetes.io/component: vep-service
  app.kubernetes.io/name: vep-annotation-service
  app.kubernetes.io/version: "1.0.0"

# VEP-specific annotations
commonAnnotations:
  app.openshift.io/runtime: quarkus
  app.openshift.io/runtime-version: "3.8"
  insights.openshift.io/billing-model: chargeback
  insights.openshift.io/cost-center: genomics-research
  insights.openshift.io/project: vep-annotation-v1
  deployment-method: "deployment"  # Updated: Using regular deployment + KEDA
  adr-decision: "ADR-001-UPDATED"  # Track architectural decision update

# VEP service image configuration
images:
  - name: vep-service
    newName: image-registry.openshift-image-registry.svc:5000/healthcare-ml-demo/vep-service
    newTag: latest

# Updated: Resource configuration in deployment.yaml for KEDA scaling
# KEDA will manage replica scaling based on Kafka lag
