apiVersion: v1
kind: ServiceAccount
metadata:
  name: vep-service
  namespace: healthcare-ml-demo
  labels:
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/component: vep-service
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    adr-decision: "ADR-001"
    cost-center: "genomics-research"
    project: "vep-annotation-v1"
    deployment-method: "knative"
