apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openshift-ai-operator
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - subscription.yaml
  - dscinitalization.yaml
  - datasciencecluster.yaml
