apiVersion: apps/v1
kind: Deployment
metadata:
  name: vep-service-nodescale
  labels:
    app: vep-service-nodescale
    component: vep-processor
    scaling-mode: nodescale
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/component: genetic-processor
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    description: "High-resource VEP service designed to trigger node scaling"
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: vep-nodescale-v1
spec:
  replicas: 0  # Start at 0, KEDA will scale up
  selector:
    matchLabels:
      app: vep-service-nodescale
  template:
    metadata:
      labels:
        app: vep-service-nodescale
        component: vep-processor
        scaling-mode: nodescale
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
    spec:
      containers:
      - name: vep-service
        image: image-registry.openshift-image-registry.svc:5000/healthcare-ml-demo/vep-service:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "genetic-data-cluster-kafka-bootstrap.healthcare-ml-demo.svc.cluster.local:9092"
        - name: QUARKUS_PROFILE
          value: "prod"
        - name: SCALING_MODE
          value: "nodescale"
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

        # Optimized resource requests to trigger compute-intensive node scaling
        resources:
          requests:
            memory: "3Gi"      # 3GB memory request per pod
            cpu: "5000m"       # 5 CPU cores - exceeds smallest standard node capacity
          limits:
            memory: "4Gi"      # 4GB memory limit per pod
            cpu: "6000m"       # 6 CPU cores per pod
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Startup probe for slower initialization
        startupProbe:
          httpGet:
            path: /q/health/started
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      
      # Node affinity for compute-intensive workloads (STRICT)
      affinity:
        nodeAffinity:
          # REQUIRE compute-intensive nodes (no fallback to standard)
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload-type
                operator: In
                values: ["compute-intensive"]
          # Prefer high-memory resource profile
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: resource-profile
                operator: In
                values: ["high-memory"]
          - weight: 80
            preference:
              matchExpressions:
              - key: environment
                operator: In
                values: ["demo"]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - vep-service-nodescale
              topologyKey: kubernetes.io/hostname
      
      # Tolerations for node scaling
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vep-service-nodescale-scaler
  labels:
    app: vep-service-nodescale
    component: vep-processor
    scaling-mode: nodescale
  annotations:
    description: "KEDA scaler for node-scale VEP processing with aggressive scaling"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vep-service-nodescale
  pollingInterval: 5   # Very aggressive polling
  cooldownPeriod: 300  # 5 minutes cooldown to allow VEP processing to complete
  idleReplicaCount: 0  # Scale to zero when idle
  minReplicaCount: 0
  maxReplicaCount: 20  # High max to force node scaling (20 pods * 5 CPU = 100 cores)
  fallback:
    failureThreshold: 3
    replicas: 2
  advanced:
    restoreToOriginalReplicaCount: false
    horizontalPodAutoscalerConfig:
      name: vep-service-nodescale-hpa
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300  # 5 minutes stabilization
          policies:
          - type: Percent
            value: 25
            periodSeconds: 60  # Slower scale-down
        scaleUp:
          stabilizationWindowSeconds: 0    # Immediate scale up
          policies:
          - type: Percent
            value: 1000  # 1000% increase = 10x scaling
            periodSeconds: 5
          - type: Pods
            value: 10    # Add 10 pods at once (10 * 5 CPU = 50 cores)
            periodSeconds: 5
          selectPolicy: Max
  triggers:
  # Primary trigger: Kafka topic lag for genetic-nodescale-raw
  - type: kafka
    metadata:
      bootstrapServers: genetic-data-cluster-kafka-bootstrap.healthcare-ml-demo.svc.cluster.local:9092
      consumerGroup: vep-nodescale-service-group
      topic: genetic-nodescale-raw
      lagThreshold: '1'  # Scale immediately on any lag
      offsetResetPolicy: latest
      allowIdleConsumers: 'false'
      scaleToZeroOnInvalidOffset: 'true'
      excludePersistentLag: 'false'

---
apiVersion: v1
kind: Service
metadata:
  name: vep-service-nodescale
  labels:
    app: vep-service-nodescale
    component: vep-processor
    scaling-mode: nodescale
  annotations:
    description: "Service for high-resource VEP node scaling demo"
spec:
  selector:
    app: vep-service-nodescale
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
