---
# Big Data Mode VEP Service Deployment
# SEPARATION OF CONCERNS: Dedicated to BIG DATA scaling mode only
# - UI Button: #bigDataModeBtn → setBigDataMode()
# - Kafka Topic: genetic-bigdata-raw (exclusive)
# - KEDA ScaledObject: vep-service-bigdata-scaler
# - Consumer Group: vep-bigdata-service-group (isolated)
# - Purpose: Memory-intensive processing for large genetic datasets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vep-service-bigdata
  labels:
    app: vep-service
    mode: bigdata
    component: vep-annotation
    scaling-mode: bigdata
    app.kubernetes.io/name: vep-annotation-service
    app.kubernetes.io/component: genetic-processor
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
    separation-of-concerns: "enforced"
  annotations:
    description: "Big data mode VEP service for memory-intensive genetic processing"
    separation-mode: "bigdata"
    separation-rationale: "Dedicated to large datasets requiring high memory allocation"
    insights.openshift.io/billing-model: "chargeback"
    insights.openshift.io/cost-center: "genomics-research"
    insights.openshift.io/project: "bigdata-mode-processing"
spec:
  replicas: 0  # Start at 0, KEDA will scale up when messages arrive
  selector:
    matchLabels:
      app: vep-service
      mode: bigdata
  template:
    metadata:
      labels:
        app: vep-service
        mode: bigdata
        component: vep-annotation
        scaling-mode: bigdata
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
    spec:
      containers:
      - name: vep-service
        image: image-registry.openshift-image-registry.svc:5000/healthcare-ml-demo/vep-service:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "genetic-data-cluster-kafka-bootstrap.healthcare-ml-demo.svc.cluster.local:9092"
        - name: VEP_MODE
          value: "bigdata"
        - name: QUARKUS_PROFILE
          value: "prod"
        - name: SCALING_MODE
          value: "bigdata"
        - name: JAVA_OPTS
          value: "-Xmx1536m -Xms1536m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
        # Higher resource allocation for big data processing
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30

---
# Service for Big Data Mode VEP
apiVersion: v1
kind: Service
metadata:
  name: vep-service-bigdata
  labels:
    app: vep-service
    mode: bigdata
    component: vep-annotation
    scaling-mode: bigdata
  annotations:
    description: "Service for big data mode VEP processing"
    separation-mode: "bigdata"
spec:
  selector:
    app: vep-service
    mode: bigdata
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
