# TEMPLATE: Compute-Intensive MachineSet for Node Scaling Demo
# 
# This template creates a cost-effective compute-intensive machine set that works across environments.
# 
# BEFORE DEPLOYING:
# 1. Replace {{CLUSTER_NAME}} with your cluster name (oc get infrastructure cluster -o jsonpath='{.status.infrastructureName}')
# 2. Replace {{REGION}} with your region (oc get infrastructure cluster -o jsonpath='{.status.platformStatus.azure.region}')
# 3. Replace {{RESOURCE_GROUP}} with your resource group
# 4. Replace {{NETWORK_RESOURCE_GROUP}} with your network resource group
# 5. Adjust vmSize based on your cloud provider and cost requirements
#
# Cost-optimized for demo purposes - using smaller instances to reduce costs
#
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: "{{CLUSTER_NAME}}-worker-compute-intensive-{{REGION}}1"
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: "{{CLUSTER_NAME}}"
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  annotations:
    description: "Cost-optimized compute-intensive machine set for healthcare ML node scaling demo"
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: node-scaling-demo
spec:
  replicas: 0  # Start with 0, autoscaler will provision when needed
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: "{{CLUSTER_NAME}}"
      machine.openshift.io/cluster-api-machineset: "{{CLUSTER_NAME}}-worker-compute-intensive-{{REGION}}1"
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: "{{CLUSTER_NAME}}"
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: "{{CLUSTER_NAME}}-worker-compute-intensive-{{REGION}}1"
    spec:
      taints: []
      metadata:
        labels:
          # These labels will be applied to the node - CRITICAL for separation of concerns
          workload-type: compute-intensive
          resource-profile: high-memory
          billing-model: chargeback
          cost-center: genomics-research
          workload.healthcare-ml/type: genetic-analysis
          workload.healthcare-ml/mode: nodescale
          workload.healthcare-ml/priority: high
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          kind: AzureMachineProviderSpec  # Change to AWSMachineProviderSpec for AWS, etc.
          location: "{{REGION}}"
          vmSize: Standard_D8s_v3  # UPGRADED: 8 vCPU, 32GB RAM to support 7-core pod requirements
          # Alternative options:
          # - Standard_D2s_v3: 2 vCPU, 8GB RAM (cheapest)
          # - Standard_D4s_v3: 4 vCPU, 16GB RAM (too small for nodescale mode)
          # - Standard_D8s_v3: 8 vCPU, 32GB RAM (chosen for 7-core VEP nodescale pods)
          vnet: "{{VNET_NAME}}"  # Replace with your VNet name
          subnet: worker-subnet  # Typically stays the same
          zone: "1"
          acceleratedNetworking: true
          image:
            # Use cluster's current image - get with: oc get machineset -o yaml | grep -A5 image
            publisher: azureopenshift
            offer: aro4
            sku: aro_414
            version: 414.92.20240213
            type: MarketplaceNoPlan
          osDisk:
            osType: Linux
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
          publicIP: false
          publicLoadBalancer: "{{CLUSTER_NAME}}"
          resourceGroup: "{{RESOURCE_GROUP}}"
          networkResourceGroup: "{{NETWORK_RESOURCE_GROUP}}"
          userDataSecret:
            name: worker-user-data
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: compute-intensive-{{REGION}}1-autoscaler
  namespace: openshift-machine-api
  annotations:
    description: "Cost-optimized machine autoscaler for compute-intensive workloads"
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: node-scaling-demo
spec:
  minReplicas: 0   # Scale to zero when no workloads - COST SAVINGS
  maxReplicas: 2   # Maximum 2 nodes to control costs (was 3)
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: "{{CLUSTER_NAME}}-worker-compute-intensive-{{REGION}}1"
