apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: custom-metrics-autoscaler-operator
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - subscription.yaml
  - openshift-keda-namespace.yaml
  - kedacontroller.yaml
