apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openshift-ai
  annotations:
    config.kubernetes.io/local-config: "true"

# OpenShift AI Resources
resources:
  - data-science-project.yaml
  - notebook-server.yaml
  - model-server.yaml
  - inference-service.yaml
  - storage.yaml

# OpenShift AI specific labels
commonLabels:
  app.kubernetes.io/component: openshift-ai
  app.kubernetes.io/name: genetic-risk-ml
  app.kubernetes.io/version: "1.0.0"
  opendatahub.io/component: "true"

# OpenShift AI specific annotations
commonAnnotations:
  opendatahub.io/notebook-image-order: "1"
  opendatahub.io/notebook-image-name: "Genetic Analysis Workbench"
  insights.openshift.io/billing-model: chargeback
  insights.openshift.io/cost-center: genomics-research
  insights.openshift.io/project: genetic-ml-v1
