apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: genetic-risk-model
  labels:
    app.kubernetes.io/component: openshift-ai
    app.kubernetes.io/name: genetic-risk-ml
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
    opendatahub.io/component: "true"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: genetic-ml-v1
    openshift.io/display-name: "Genetic Risk Prediction Model"
    openshift.io/description: "ML model for predicting genetic risk based on VEP annotations"
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: mlserver-1.x
      storage:
        key: genetic-models-storage
        path: genetic-risk-model
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      env:
        - name: MLSERVER_MODEL_NAME
          value: genetic-risk-model
        - name: MLSERVER_MODEL_URI
          value: /mnt/models/genetic-risk-model
        - name: MLSERVER_MODEL_IMPLEMENTATION
          value: mlserver_sklearn.SKLearnModel
        - name: MLSERVER_HTTP_PORT
          value: "8080"
        - name: MLSERVER_GRPC_PORT
          value: "8081"
        - name: MLSERVER_METRICS_PORT
          value: "8082"
        - name: MLSERVER_DEBUG
          value: "false"
      # Model metadata
      protocolVersion: v2
      runtimeVersion: "1.3.5"
---
apiVersion: v1
kind: Service
metadata:
  name: genetic-risk-model-predictor
  labels:
    app.kubernetes.io/component: openshift-ai
    app.kubernetes.io/name: genetic-risk-ml
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
    opendatahub.io/component: "true"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: genetic-ml-v1
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: metrics
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: genetic-risk-model
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genetic-ml-pipeline
  labels:
    app.kubernetes.io/component: openshift-ai
    app.kubernetes.io/name: genetic-risk-ml
    app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
    app.kubernetes.io/version: "1.0.0"
  annotations:
    insights.openshift.io/billing-model: chargeback
    insights.openshift.io/cost-center: genomics-research
    insights.openshift.io/project: genetic-ml-v1
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: genetic-ml-pipeline-role
  labels:
    app.kubernetes.io/component: openshift-ai
    app.kubernetes.io/name: genetic-risk-ml
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["kubeflow.org"]
    resources: ["notebooks"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genetic-ml-pipeline-binding
  labels:
    app.kubernetes.io/component: openshift-ai
    app.kubernetes.io/name: genetic-risk-ml
subjects:
  - kind: ServiceAccount
    name: genetic-ml-pipeline
    namespace: genetic-risk-prediction
roleRef:
  kind: Role
  name: genetic-ml-pipeline-role
  apiGroup: rbac.authorization.k8s.io
