apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: quarkus-websocket-service
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - configmap.yaml
  - imagestream.yaml
  - buildconfig.yaml
  # ADR-001: WebSocket Service uses Deployment for persistent connections
  - deployment.yaml            # Standard Kubernetes Deployment (ADR-001)
  - service.yaml              # Service for load balancing
  - route.yaml                # OpenShift Route for external access
  # - deploymentconfig.yaml    # OpenShift DeploymentConfig (alternative)
  # - knative-service.yaml     # Knative Service (moved to VEP service per ADR-001)
  # Note: Deployment + Service + Route provides persistent WebSocket connections

# Common labels for all Quarkus WebSocket service resources
labels:
  - pairs:
      app.kubernetes.io/name: quarkus-websocket-service
      app.kubernetes.io/part-of: healthcare-ml-demo
      app.kubernetes.io/component: websocket-service

# Common annotations for cost management
commonAnnotations:
  cost-center: "genomics-research"
  project: "risk-predictor-v1"
  deployment-method: "deployment"  # ADR-001: Changed from knative to deployment
  adr-decision: "ADR-001"          # Track architectural decision

# Image management for OpenShift BuildConfig integration
# Note: When using BuildConfig, the image is managed by the ImageStream
# For external registries, uncomment and modify the following:
# images:
#   - name: quarkus-websocket-service
#     newName: quay.io/healthcare-ml/genetic-risk-predictor-ws
#     newTag: latest
