apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keda-scaler
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - scaledobject.yaml

# Common labels for all KEDA scaler resources
labels:
  - pairs:
      app.kubernetes.io/name: keda-scaler
      app.kubernetes.io/part-of: healthcare-ml-genetic-predictor
      app.kubernetes.io/component: autoscaler

# Common annotations for cost management
commonAnnotations:
  insights.openshift.io/cost-center: "genomics-research"
  insights.openshift.io/project: "risk-predictor-v1"
  insights.openshift.io/billing-model: "chargeback"
  deployment-method: "kustomize"
