apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keda-scaler
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  # Will contain:
  # - scaledobject.yaml

# Placeholder - resources will be added in Task 6
