apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: healthcare-ml-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Namespace for all resources
namespace: healthcare-ml-demo

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: healthcare-ml-demo
  app.kubernetes.io/part-of: genetic-risk-predictor
  app.kubernetes.io/managed-by: kustomize

# Common annotations for cost management
commonAnnotations:
  cost-center: "genomics-research"
  project: "risk-predictor-v1"
  deployment-method: "kustomize"
  openshift.io/display-name: "Healthcare ML Demo"

# ADR-001 Compliant Resources
resources:
  # Build Configurations
  - buildconfigs/websocket-service-bc.yaml
  - buildconfigs/vep-service-bc.yaml
  # Core Services (ADR-001 Architecture)
  - websocket-service/deployment.yaml    # WebSocket as Deployment (persistent connections)
  - vep-service/knative-service.yaml     # VEP as Knative Service (scale-to-zero)
  - keda/scaledobject.yaml               # KEDA scaling for both services
  - kafka/topics.yaml                    # Kafka topics for data flow

# Components for reusable configurations
components:
  - ../components/cost-labels
  - ../components/security-context

# Images to be managed (can be overridden in overlays)
images:
  - name: quarkus-websocket-service
    newName: quay.io/healthcare-ml/genetic-risk-predictor-ws
    newTag: latest
  - name: vep-service
    newName: quay.io/healthcare-ml/vep-annotation-service
    newTag: latest
  - name: ml-inference-service
    newName: quay.io/healthcare-ml/ml-inference-service
    newTag: latest
  - name: frontend-nginx
    newName: nginx
    newTag: "1.25-alpine"

# Configuration for generating ConfigMaps and Secrets
configMapGenerator: []
secretGenerator: []

# Patches to be applied (can be extended in overlays)
patches: []

# Replacements for cross-resource field references
replacements: []

# Build metadata
buildMetadata:
  - originAnnotations
  - transformerAnnotations
  - managedByLabel
