apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: keda-scalers
  annotations:
    config.kubernetes.io/local-config: "true"
    description: "KEDA ScaledObjects for healthcare ML genetic analysis scaling"

# KEDA ScaledObject Resources
resources:
  - scaledobject.yaml
  - vep-bigdata-scaler.yaml

# KEDA-specific labels
labels:
  - pairs:
      app.kubernetes.io/component: keda-scaler
      app.kubernetes.io/name: healthcare-ml-scalers
      app.kubernetes.io/version: "1.0.0"

# KEDA-specific annotations
commonAnnotations:
  insights.openshift.io/billing-model: chargeback
  insights.openshift.io/cost-center: genomics-research
  insights.openshift.io/project: healthcare-ml-keda-v1
  deployment-method: "keda-kustomize"
  github-issue: "21"
