apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: healthcare-ml-staging
  annotations:
    config.kubernetes.io/local-config: "true"

# Reference to base configuration
resources:
  - ../../base

# Staging-specific configurations
namePrefix: staging-
nameSuffix: ""

# Staging environment labels
commonLabels:
  environment: "staging"
  deployment-tier: "staging"

# Staging-specific patches
patches:
  # Will contain:
  # - Production-like resource allocation
  # - Persistent storage
  # - Performance monitoring
  # - Multiple replicas for testing

# Staging-specific images (use release candidates)
images:
  - name: quarkus-websocket-service
    newTag: staging-v1.0.0-rc1
  - name: ml-inference-service
    newTag: staging-v1.0.0-rc1

# Placeholder - will be enhanced in Task 7
